<?php

use Domain\Currency\Currency;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    public function run()
    {
        $rows = [
            [
                'code' => 'USD',
                'symbol' => '$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'AED',
                'symbol' => 'د.إ',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'ALL',
                'symbol' => 'Lek',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'AMD',
                'symbol' => '֏',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'ANG',
                'symbol' => 'ƒ',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'AUD',
                'symbol' => '$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'AWG',
                'symbol' => 'ƒ',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'AZN',
                'symbol' => '₼',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'BAM',
                'symbol' => 'KM',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'BBD',
                'symbol' => '$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'BDT',
                'symbol' => 'Tk',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'BGN',
                'symbol' => 'лв',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'BIF',
                'symbol' => null,
                'factor' => 1,
                'decimals' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'BMD',
                'symbol' => '$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'BND',
                'symbol' => '$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'BSD',
                'symbol' => '$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'BWP',
                'symbol' => 'P',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'BZD',
                'symbol' => 'BZ$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'CAD',
                'symbol' => '$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'CDF',
                'symbol' => null,
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'CHF',
                'symbol' => 'CHF',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'CNY',
                'symbol' => '¥',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'DKK',
                'symbol' => 'kr.',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'DOP',
                'symbol' => 'RD$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'DZD',
                'symbol' => null,
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'EGP',
                'symbol' => '£',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'ETB',
                'symbol' => 'Br',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'EUR',
                'symbol' => '€',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'FJD',
                'symbol' => '$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'GBP',
                'symbol' => '£',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'GEL',
                'symbol' => null,
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'GIP',
                'symbol' => '£',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'GMD',
                'symbol' => null,
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'GYD',
                'symbol' => '$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'HKD',
                'symbol' => 'HK$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'HRK',
                'symbol' => 'kn',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'HTG',
                'symbol' => 'G',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'IDR',
                'symbol' => 'Rp',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'ILS',
                'symbol' => '₪',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'ISK',
                'symbol' => 'kr',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'JMD',
                'symbol' => 'J$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'JPY',
                'symbol' => '¥',
                'factor' => 1,
                'decimals' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'KES',
                'symbol' => 'KSh',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'KGS',
                'symbol' => 'лв',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'KHR',
                'symbol' => '៛',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'KMF',
                'symbol' => null,
                'factor' => 1,
                'decimals' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'KRW',
                'symbol' => '₩',
                'factor' => 1,
                'decimals' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'KYD',
                'symbol' => '$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'KZT',
                'symbol' => '₸',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'LBP',
                'symbol' => 'ل.ل.‎',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'LKR',
                'symbol' => 'Rs',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'LRD',
                'symbol' => '$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'LSL',
                'symbol' => null,
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'MAD',
                'symbol' => 'DH',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'MDL',
                'symbol' => null,
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'MGA',
                'symbol' => 'Ar',
                'factor' => 1,
                'decimals' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'MKD',
                'symbol' => 'ден',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'MMK',
                'symbol' => 'K',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'MNT',
                'symbol' => '₮',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'MOP',
                'symbol' => 'MOP$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'MRO',
                'symbol' => 'UM',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'MVR',
                'symbol' => 'Rf',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'MWK',
                'symbol' => 'MK',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'MXN',
                'symbol' => '$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'MYR',
                'symbol' => 'RM',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'MZN',
                'symbol' => 'MT',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'NAD',
                'symbol' => '$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'NGN',
                'symbol' => '₦',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'NOK',
                'symbol' => 'kr',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'NPR',
                'symbol' => '₨',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'NZD',
                'symbol' => '$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'PGK',
                'symbol' => 'K',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'PHP',
                'symbol' => '₱',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'PKR',
                'symbol' => '₨',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'PLN',
                'symbol' => 'zł',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'QAR',
                'symbol' => '﷼',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'RON',
                'symbol' => 'lei',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'RSD',
                'symbol' => 'РСД',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'RUB',
                'symbol' => '₽',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'RWF',
                'symbol' => 'FRw',
                'factor' => 1,
                'decimals' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'SAR',
                'symbol' => '﷼',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'SBD',
                'symbol' => '$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'SCR',
                'symbol' => '₨',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'SEK',
                'symbol' => 'kr',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'SGD',
                'symbol' => '$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'SLL',
                'symbol' => 'Le',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'SOS',
                'symbol' => 'S',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'STD',
                'symbol' => 'Db',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'SZL',
                'symbol' => 'L',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'THB',
                'symbol' => '฿',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'TJS',
                'symbol' => null,
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'TOP',
                'symbol' => 'T$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'TRY',
                'symbol' => '₺',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'TTD',
                'symbol' => 'TT$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'TWD',
                'symbol' => 'NT$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'TZS',
                'symbol' => 'TSh',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'UAH',
                'symbol' => '₴',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'UGX',
                'symbol' => 'UGX',
                'factor' => 1,
                'decimals' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'UZS',
                'symbol' => 'лв',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'VND',
                'symbol' => '₫',
                'factor' => 1,
                'decimals' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'VUV',
                'symbol' => 'VT',
                'factor' => 1,
                'decimals' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'WST',
                'symbol' => '$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'XAF',
                'symbol' => 'FCFA',
                'factor' => 1,
                'decimals' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'XCD',
                'symbol' => '$',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'YER',
                'symbol' => '﷼',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'ZAR',
                'symbol' => 'R',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'code' => 'ZMW',
                'symbol' => 'ZK',
                'factor' => 100,
                'decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        Currency::insert($rows);
    }
}
